[build]
  command = "sed -i \"s/%GITHUB_TOKEN%/$GITHUB_TOKEN/g\" public/env.js && npm run build"
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 